Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import datetime
import pytz

df_quantification = df_predictions[['time', 'pred_arm_at_rest', 'pred_tremor_checked','tremor_power']].copy()
df_quantification.loc[df_predictions['pred_tremor_checked'] == 0, 'tremor_power'] = None # tremor power of non-tremor windows is set to None

# Create datetime column based on the start time of the segment
start_time = datetime.datetime.strptime(metadata_time.start_iso8601, '%Y-%m-%dT%H:%M:%SZ')
start_time = start_time.replace(tzinfo=pytz.timezone('UTC')).astimezone(pytz.timezone('CET')) # convert to correct timezone if necessary
df_quantification['time_dt'] = start_time + pd.to_timedelta(df_quantification['time'], unit="s") 
df_quantification = df_quantification[['time', 'time_dt', 'pred_arm_at_rest', 'pred_tremor_checked', 'tremor_power']]

df_quantification
------------------


[31m---------------------------------------------------------------------------[39m
[31mKeyError[39m                                  Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[7][39m[32m, line 5[39m
[32m      2[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mdatetime[39;00m
[32m      3[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpytz[39;00m
[32m----> [39m[32m5[39m df_quantification = [43mdf_predictions[49m[43m[[49m[43m[[49m[33;43m'[39;49m[33;43mtime[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[33;43m'[39;49m[33;43mpred_arm_at_rest[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[33;43m'[39;49m[33;43mpred_tremor_checked[39;49m[33;43m'[39;49m[43m,[49m[33;43m'[39;49m[33;43mtremor_power[39;49m[33;43m'[39;49m[43m][49m[43m][49m.copy()
[32m      6[39m df_quantification.loc[df_predictions[[33m'[39m[33mpred_tremor_checked[39m[33m'[39m] == [32m0[39m, [33m'[39m[33mtremor_power[39m[33m'[39m] = [38;5;28;01mNone[39;00m [38;5;66;03m# tremor power of non-tremor windows is set to None[39;00m
[32m      8[39m [38;5;66;03m# Create datetime column based on the start time of the segment[39;00m

[36mFile [39m[32m~/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/pandas/core/frame.py:4108[39m, in [36mDataFrame.__getitem__[39m[34m(self, key)[39m
[32m   4106[39m     [38;5;28;01mif[39;00m is_iterator(key):
[32m   4107[39m         key = [38;5;28mlist[39m(key)
[32m-> [39m[32m4108[39m     indexer = [38;5;28;43mself[39;49m[43m.[49m[43mcolumns[49m[43m.[49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[33;43m"[39;49m[33;43mcolumns[39;49m[33;43m"[39;49m[43m)[49m[[32m1[39m]
[32m   4110[39m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[32m   4111[39m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [33m"[39m[33mdtype[39m[33m"[39m, [38;5;28;01mNone[39;00m) == [38;5;28mbool[39m:

[36mFile [39m[32m~/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py:6200[39m, in [36mIndex._get_indexer_strict[39m[34m(self, key, axis_name)[39m
[32m   6197[39m [38;5;28;01melse[39;00m:
[32m   6198[39m     keyarr, indexer, new_indexer = [38;5;28mself[39m._reindex_non_unique(keyarr)
[32m-> [39m[32m6200[39m [38;5;28;43mself[39;49m[43m.[49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[32m   6202[39m keyarr = [38;5;28mself[39m.take(indexer)
[32m   6203[39m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[32m   6204[39m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

[36mFile [39m[32m~/.cache/pypoetry/virtualenvs/paradigma-1HID61PK-py3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py:6252[39m, in [36mIndex._raise_if_missing[39m[34m(self, key, indexer, axis_name)[39m
[32m   6249[39m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([33mf[39m[33m"[39m[33mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[33m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[33m][39m[33m"[39m)
[32m   6251[39m not_found = [38;5;28mlist[39m(ensure_index(key)[missing_mask.nonzero()[[32m0[39m]].unique())
[32m-> [39m[32m6252[39m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([33mf[39m[33m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[33m not in index[39m[33m"[39m)

[31mKeyError[39m: "['tremor_power'] not in index"

